[package]
name = "wlitem"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = {version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
url = { version = "2.5.8", features = ["serde"] }
uuid = { version = "1.20.0", features = ["v4"] }
